"""Shared "record one run into lineage + the run index" helper.

Both the CLI/workbench path (:class:`quant_forge.workbench.service.WorkbenchService`)
and the local web adapter (:mod:`quant_forge.apps.web.api`) produce the same
kinds of run evidence (evaluate/backtest/composite-backtest artifacts) and
must leave the same :class:`~quant_forge.lineage.store.LineageStore` +
:class:`~quant_forge.lineage.store.RunIndex` trail, or ``qf runs``, the
registry detail view, and the web "研究历史" (research history) panel only
ever see CLI-originated runs (BUG #007). This module is the one place that
builds that trail; callers supply the paths, the already-computed
request/highlights/data_window, and get back the appended run-index row.

``WorkbenchService._record_run`` calls :func:`record_run` instead of
inlining this logic, so the CLI path and the web path share one
implementation instead of two that can silently drift apart.
"""

from __future__ import annotations

from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping

from quant_forge.factor_library.catalog import FactorCatalog
from quant_forge.lineage.store import (
    LineageRecord,
    LineageStore,
    RunIndex,
    canonical_fingerprint,
    locate_factor_definition_file,
    new_run_id,
)


def record_run(
    *,
    factor_root: Path,
    artifact_root: Path,
    factor_values_root: Path | None = None,
    factor_values_manifest_root: Path | None = None,
    kind: str,
    factor_id: str,
    artifact_type: str,
    artifact_path: Path,
    generated_by: str,
    request: Mapping[str, Any],
    metric_highlights: Mapping[str, Mapping[str, Any]],
    data_window: Mapping[str, Any],
    warnings_count: int,
) -> dict[str, Any]:
    """Record one factor-definition lineage edge, one artifact edge, and one
    run-index row for a completed run.

    Mirrors the pre-extraction ``WorkbenchService._record_run`` /
    ``_record_factor_definition`` exactly: same fingerprinting
    (``canonical_fingerprint(request)``), same factor-definition lookup with
    a ``FactorCatalog`` fallback when the definition file cannot be located
    on disk, same ``RunIndex.append_run`` call shape. ``created_at`` is
    generated here (run history is bookkeeping, not evaluation input).

    No exception handling here by design: a recording failure is a real
    failure and must propagate, exactly like the workbench call sites this
    replaces (see workbench.service.WorkbenchService._record_run, which never
    wrapped this in a try/except either).
    """

    created_at = datetime.now(timezone.utc)
    created_at_iso = created_at.isoformat()
    fingerprint = canonical_fingerprint(request)
    store = LineageStore(artifact_root)
    definition_record = _record_factor_definition(
        store,
        factor_root=factor_root,
        factor_values_root=factor_values_root,
        factor_values_manifest_root=factor_values_manifest_root,
        factor_id=factor_id,
        created_at_iso=created_at_iso,
    )
    artifact_record = store.record_artifact(
        artifact_type=artifact_type,
        path=artifact_path,
        created_at=created_at_iso,
        generated_by=generated_by,
        parents=(definition_record.artifact_id,),
    )
    return RunIndex(artifact_root).append_run(
        run_id=new_run_id(kind, created_at, fingerprint),
        kind=kind,
        factor_ids=(factor_id,),
        created_at=created_at_iso,
        data_window=data_window,
        config_fingerprint=fingerprint,
        metric_highlights=metric_highlights,
        artifact_paths_rel=(artifact_record.path_rel,) if artifact_record.path_rel else (),
        warnings_count=warnings_count,
    )


def _record_factor_definition(
    store: LineageStore,
    *,
    factor_root: Path,
    factor_values_root: Path | None,
    factor_values_manifest_root: Path | None,
    factor_id: str,
    created_at_iso: str,
) -> LineageRecord:
    path = locate_factor_definition_file(factor_root, factor_id)
    payload: dict[str, object] | None = None
    if path is None:
        definition = FactorCatalog(
            factor_root,
            factor_values_root=factor_values_root,
            factor_values_manifest_root=factor_values_manifest_root,
        ).get(factor_id)
        payload = asdict(definition)
    # The definition is sourced from factor_root, not generated by this run;
    # a stable generated_by also deduplicates the root lineage row.
    return store.record_artifact(
        artifact_type="factor_definition",
        path=path,
        payload=payload,
        created_at=created_at_iso,
        generated_by="factor_root",
    )
